export const sliderItems = [
    {
        id: 1,
        img1: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FBANNER_NETFLIX_BG.jpg&w=1920&q=90',
        img2: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FNETFLIX_3D.png&w=1920&q=90',
        title1: 'SHARE TÀI KHOÁN NETFLIX',
        title2: 'XEM PHIM CHIẾU RẠP',
        title3: 'VỚI GÓI NETFLIX PREMIUM',
        desc: 'Tận hưởng trải nghiệm xem phim chất lượng Ultra HD 4K, âm thanh 5.1. Dịch vụ uy tín, nhanh nhẹn và ổn định',
        title_btn1: 'NETFLIX SHARE',
        title_btn2: 'THỬ NGAY',
        color: '#ff0000',
        slug: 'netflix',
        slug1: 'goi-netflix-premium-gia-dinh-1-thang',
    },
    {
        id: 2,
        img1: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FBANNER_SPOTIFY_BG.jpg&w=1920&q=90',
        img2: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FSPOTIFY_3D.png&w=1920&q=90',
        title1: 'SHARE TÀI KHOÁN NETFLIX',
        title2: 'XEM PHIM CHIẾU RẠP',
        title3: 'VỚI GÓI SPOTIFY PREMIUM',
        desc: 'Tận hưởng trải nghiệm xem phim chất lượng Ultra HD 4K, âm thanh 5.1. Dịch vụ uy tín, nhanh nhẹn và ổn định',
        title_btn1: 'SPOTIFY SHARE',
        title_btn2: 'THỬ NGAY',
        color: '#02fc0f',
        slug: 'spotify',
        slug1: 'goi-spotify-premium-vip-4-thang',
    },
    {
        id: 3,
        img1: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FBANNER_YOUTUBE_BG.jpg&w=1920&q=90',
        img2: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FYOUTUBE_3D.png&w=1920&q=90',
        title1: 'SHARE TÀI KHOÁN NETFLIX',
        title2: 'XEM PHIM CHIẾU RẠP',
        title3: 'VỚI GÓI YOUTUBE PREMIUM',
        desc: 'Tận hưởng trải nghiệm xem phim chất lượng Ultra HD 4K, âm thanh 5.1. Dịch vụ uy tín, nhanh nhẹn và ổn định',
        title_btn1: 'YOUTUBE SHARE',
        title_btn2: 'THỬ NGAY',
        color: '#ff0000',
        slug: 'youtube',
        slug1: 'goi-youtube-premium-3-thang',
    },
    {
        id: 4,
        img1: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FBANNER_BG_TIDAL.jpg&w=1920&q=90',
        img2: 'https://vietplayplus.com/_next/image?url=%2Fimages%2FTIDAL_3D.png&w=1920&q=90',
        title1: 'SHARE TÀI KHOÁN NETFLIX',
        title2: 'XEM PHIM CHIẾU RẠP',
        title3: 'VỚI GÓI TIDAL PREMIUM',
        desc: 'Tận hưởng trải nghiệm xem phim chất lượng Ultra HD 4K, âm thanh 5.1. Dịch vụ uy tín, nhanh nhẹn và ổn định',
        title_btn1: 'TIDAL SHARE',
        title_btn2: 'THỬ NGAY',
        color: '#00ffd5',
        slug: 'tidal',
        slug2: 'goi-tidal-hifi-plus-3-thang',
    },
];

export const categories = [
    {
        isMenu: true,
        visible: true,
        name: 'NETFLIX',
        slug: 'netflix',
        description: 'NETFLIX',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1000,
                    height: 750,
                    size: 23746,
                    url: 'public/files/photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    name: 'photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 690,
                    size: 15347,
                    url: 'public/files/medium_photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    name: 'medium_photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 480,
                    size: 9403,
                    url: 'public/files/small_photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    name: 'small_photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 255,
                    size: 4226,
                    url: 'public/files/thumbnails_photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    name: 'thumbnails_photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 1000,
            height: 750,
            size: 23746,
            url: 'public/files/photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
            name: 'photo-1611162617474-5b21e879e113_0L14K72Zf.jpg',
            mimetype: 'image/jpeg',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-02-10T06:53:46.766Z',
            updatedAt: '2022-02-10T06:53:46.766Z',
            id: '6204b67a7d3ba67f4f424fe6',
        },
        createdAt: '2021-09-08T15:02:40.482Z',
        updatedAt: '2022-02-10T06:55:20.023Z',
        id: '6138d090c1070024b7750c02',
    },
    {
        isMenu: true,
        visible: true,
        name: 'SPOTIFY',
        slug: 'spotify',
        description: 'SPOTIFY',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 46922,
                    url: 'public/files/large_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    name: 'large_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 26903,
                    url: 'public/files/medium_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    name: 'medium_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 17198,
                    url: 'public/files/small_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    name: 'small_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 7815,
                    url: 'public/files/thumbnails_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    name: 'thumbnails_DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 253784,
            url: 'public/files/DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
            name: 'DanhMuc_SPOTIFY_ouQ0dDcH4.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-08T15:05:52.667Z',
            updatedAt: '2021-09-08T15:05:52.667Z',
            id: '6138d150c1070024b7750c03',
        },
        createdAt: '2021-09-08T15:06:09.733Z',
        updatedAt: '2021-09-08T15:06:09.733Z',
        id: '6138d161c1070024b7750c05',
    },
    {
        isMenu: true,
        visible: true,
        name: 'YOUTUBE PREMIUM',
        slug: 'youtube-premium',
        description: 'YOUTUBE PREMIUM',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 37425,
                    url: 'public/files/large_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    name: 'large_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 20963,
                    url: 'public/files/medium_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    name: 'medium_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 12909,
                    url: 'public/files/small_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    name: 'small_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 5868,
                    url: 'public/files/thumbnails_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    name: 'thumbnails_DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 227531,
            url: 'public/files/DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
            name: 'DanhMuc_YOUTUBE_FFlFtuCQg.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-08T15:10:16.713Z',
            updatedAt: '2021-09-08T15:10:16.713Z',
            id: '6138d258c1070024b7750c06',
        },
        createdAt: '2021-09-08T15:10:30.577Z',
        updatedAt: '2021-09-08T15:10:30.577Z',
        id: '6138d266c1070024b7750c08',
    },
    {
        isMenu: true,
        visible: true,
        name: 'CANVA',
        slug: 'canva',
        description: 'CANVA',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 45629,
                    url: 'public/files/large_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    name: 'large_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 26848,
                    url: 'public/files/medium_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    name: 'medium_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 17567,
                    url: 'public/files/small_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    name: 'small_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 7982,
                    url: 'public/files/thumbnails_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    name: 'thumbnails_DanhMuc_CANVA_XIl8D1vY6.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 237376,
            url: 'public/files/DanhMuc_CANVA_XIl8D1vY6.jpg',
            name: 'DanhMuc_CANVA_XIl8D1vY6.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-08T15:17:19.638Z',
            updatedAt: '2021-09-08T15:17:19.638Z',
            id: '6138d3ffc1070024b7750c09',
        },
        createdAt: '2021-09-08T15:17:32.796Z',
        updatedAt: '2021-09-08T15:17:32.796Z',
        id: '6138d40cc1070024b7750c0b',
    },
    {
        isMenu: true,
        visible: true,
        name: 'HBO MAX',
        slug: 'hbo-max',
        description: 'HBO MAX',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 33862,
                    url: 'public/files/large_DanhMuc_HBO_31M83SyGS.jpg',
                    name: 'large_DanhMuc_HBO_31M83SyGS.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 19534,
                    url: 'public/files/medium_DanhMuc_HBO_31M83SyGS.jpg',
                    name: 'medium_DanhMuc_HBO_31M83SyGS.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 12525,
                    url: 'public/files/small_DanhMuc_HBO_31M83SyGS.jpg',
                    name: 'small_DanhMuc_HBO_31M83SyGS.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 5749,
                    url: 'public/files/thumbnails_DanhMuc_HBO_31M83SyGS.jpg',
                    name: 'thumbnails_DanhMuc_HBO_31M83SyGS.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 205783,
            url: 'public/files/DanhMuc_HBO_31M83SyGS.jpg',
            name: 'DanhMuc_HBO_31M83SyGS.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-08T15:25:52.891Z',
            updatedAt: '2021-09-08T15:25:52.891Z',
            id: '6138d600c1070024b7750c0c',
        },
        createdAt: '2021-09-08T15:26:01.903Z',
        updatedAt: '2022-02-10T07:28:17.546Z',
        id: '6138d609c1070024b7750c0e',
    },
    {
        isMenu: true,
        visible: true,
        name: 'HULU',
        slug: 'hulu',
        description: 'HULU',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 26265,
                    url: 'public/files/large_DanhMuc_HULU_0JafqD68b.jpg',
                    name: 'large_DanhMuc_HULU_0JafqD68b.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 14689,
                    url: 'public/files/medium_DanhMuc_HULU_0JafqD68b.jpg',
                    name: 'medium_DanhMuc_HULU_0JafqD68b.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 8955,
                    url: 'public/files/small_DanhMuc_HULU_0JafqD68b.jpg',
                    name: 'small_DanhMuc_HULU_0JafqD68b.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 4215,
                    url: 'public/files/thumbnails_DanhMuc_HULU_0JafqD68b.jpg',
                    name: 'thumbnails_DanhMuc_HULU_0JafqD68b.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 193482,
            url: 'public/files/DanhMuc_HULU_0JafqD68b.jpg',
            name: 'DanhMuc_HULU_0JafqD68b.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-08T16:13:54.092Z',
            updatedAt: '2021-09-08T16:13:54.092Z',
            id: '6138e142c1070024b7750c0f',
        },
        createdAt: '2021-09-08T16:14:04.169Z',
        updatedAt: '2022-02-10T07:33:27.210Z',
        id: '6138e14cc1070024b7750c11',
    },
    {
        isMenu: true,
        visible: true,
        name: 'NAPSTER',
        slug: 'napster',
        description: 'NAPSTER',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 47868,
                    url: 'public/files/large_DanhMuc_HULU_V0DzkxTfh.jpg',
                    name: 'large_DanhMuc_HULU_V0DzkxTfh.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 27133,
                    url: 'public/files/medium_DanhMuc_HULU_V0DzkxTfh.jpg',
                    name: 'medium_DanhMuc_HULU_V0DzkxTfh.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 17609,
                    url: 'public/files/small_DanhMuc_HULU_V0DzkxTfh.jpg',
                    name: 'small_DanhMuc_HULU_V0DzkxTfh.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 7891,
                    url: 'public/files/thumbnails_DanhMuc_HULU_V0DzkxTfh.jpg',
                    name: 'thumbnails_DanhMuc_HULU_V0DzkxTfh.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 236056,
            url: 'public/files/DanhMuc_HULU_V0DzkxTfh.jpg',
            name: 'DanhMuc_HULU_V0DzkxTfh.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-08T17:00:43.620Z',
            updatedAt: '2021-09-08T17:00:43.620Z',
            id: '6138ec3bc1070024b7750c18',
        },
        createdAt: '2021-09-08T16:58:01.099Z',
        updatedAt: '2021-09-08T17:00:54.870Z',
        id: '6138eb99c1070024b7750c17',
    },
    {
        isMenu: true,
        visible: true,
        name: 'TIDAL',
        slug: 'tidal',
        description: 'TIDAL HIFI',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 44945,
                    url: 'public/files/large_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    name: 'large_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 24759,
                    url: 'public/files/medium_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    name: 'medium_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 15419,
                    url: 'public/files/small_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    name: 'small_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 6783,
                    url: 'public/files/thumbnails_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    name: 'thumbnails_DanhMuc_TIDAL_Zm0DyWtFi.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 252357,
            url: 'public/files/DanhMuc_TIDAL_Zm0DyWtFi.jpg',
            name: 'DanhMuc_TIDAL_Zm0DyWtFi.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-09T07:21:56.374Z',
            updatedAt: '2021-09-09T07:21:56.374Z',
            id: '6139b614c1070024b7750c24',
        },
        createdAt: '2021-09-08T17:43:44.419Z',
        updatedAt: '2022-02-18T14:05:22.285Z',
        id: '6138f650c1070024b7750c1b',
    },
    {
        isMenu: true,
        visible: true,
        name: 'HỌC TẬP',
        slug: 'hc-tp',
        description: 'HỌC TẬP',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 41647,
                    url: 'public/files/large_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    name: 'large_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 23976,
                    url: 'public/files/medium_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    name: 'medium_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 15298,
                    url: 'public/files/small_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    name: 'small_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 6945,
                    url: 'public/files/thumbnails_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    name: 'thumbnails_DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 228473,
            url: 'public/files/DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
            name: 'DanhMuc_EDUCATION_v1I-PbNXZ.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-09T11:24:12.195Z',
            updatedAt: '2021-09-09T11:24:12.195Z',
            id: '6139eedcc1070024b7750c2c',
        },
        createdAt: '2021-09-09T10:58:59.961Z',
        updatedAt: '2021-09-09T12:01:31.604Z',
        id: '6139e8f3c1070024b7750c27',
    },
    {
        isMenu: true,
        visible: true,
        name: 'PHẦN MỀM VPN',
        slug: 'phn-mm-vpn',
        description: 'PHẦN MỀM VPN',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1440,
                    height: 752,
                    size: 30222,
                    url: 'public/files/large_DanhMuc_VPN_o3ImuJv_2.jpg',
                    name: 'large_DanhMuc_VPN_o3ImuJv_2.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 481,
                    size: 16957,
                    url: 'public/files/medium_DanhMuc_VPN_o3ImuJv_2.jpg',
                    name: 'medium_DanhMuc_VPN_o3ImuJv_2.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 334,
                    size: 10618,
                    url: 'public/files/small_DanhMuc_VPN_o3ImuJv_2.jpg',
                    name: 'small_DanhMuc_VPN_o3ImuJv_2.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 178,
                    size: 4820,
                    url: 'public/files/thumbnails_DanhMuc_VPN_o3ImuJv_2.jpg',
                    name: 'thumbnails_DanhMuc_VPN_o3ImuJv_2.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 2500,
            height: 1306,
            size: 207416,
            url: 'public/files/DanhMuc_VPN_o3ImuJv_2.jpg',
            name: 'DanhMuc_VPN_o3ImuJv_2.jpg',
            mimetype: 'image/jpeg',
            user: '60fc13cd7786015ba4615963',
            createdAt: '2021-09-09T12:44:12.526Z',
            updatedAt: '2021-09-09T12:44:12.526Z',
            id: '613a019cc1070024b7750c2d',
        },
        createdAt: '2021-09-09T12:44:22.664Z',
        updatedAt: '2021-09-09T12:44:22.664Z',
        id: '613a01a6c1070024b7750c2f',
    },
    {
        isMenu: true,
        visible: true,
        name: 'WINDOWS BẢN QUYỀN',
        slug: 'windows-bn-quyn',
        description: 'Windows Bản Quyền',
        image: {
            formats: {
                large: {
                    format: 'png',
                    width: 1200,
                    height: 630,
                    size: 135727,
                    url: 'public/files/windows-logo-social_i5ReUzyMm.png',
                    name: 'windows-logo-social_i5ReUzyMm.png',
                    mimetype: 'image/png',
                },
                medium: {
                    format: 'png',
                    width: 920,
                    height: 483,
                    size: 78972,
                    url: 'public/files/medium_windows-logo-social_i5ReUzyMm.png',
                    name: 'medium_windows-logo-social_i5ReUzyMm.png',
                    mimetype: 'image/png',
                },
                small: {
                    format: 'png',
                    width: 640,
                    height: 336,
                    size: 35139,
                    url: 'public/files/small_windows-logo-social_i5ReUzyMm.png',
                    name: 'small_windows-logo-social_i5ReUzyMm.png',
                    mimetype: 'image/png',
                },
                thumbnails: {
                    format: 'png',
                    width: 340,
                    height: 179,
                    size: 8283,
                    url: 'public/files/thumbnails_windows-logo-social_i5ReUzyMm.png',
                    name: 'thumbnails_windows-logo-social_i5ReUzyMm.png',
                    mimetype: 'image/png',
                },
            },
            alternativeText: '',
            format: 'png',
            width: 1200,
            height: 630,
            size: 135727,
            url: 'public/files/windows-logo-social_i5ReUzyMm.png',
            name: 'windows-logo-social_i5ReUzyMm.png',
            mimetype: 'image/png',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-01-28T15:05:12.991Z',
            updatedAt: '2022-01-28T15:05:12.991Z',
            id: '61f406287d3ba67f4f4247e9',
        },
        createdAt: '2022-01-28T15:04:05.019Z',
        updatedAt: '2022-01-28T15:33:30.384Z',
        id: '61f405e57d3ba67f4f4247e8',
    },
    {
        isMenu: true,
        visible: true,
        name: 'PHẦN MỀM DIỆT VIRUS',
        slug: 'phn-mm-dit-virus',
        description: 'PHẦN MỀM DIỆT VIRUS AN TOÀN CHO MÁY TÍNH',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1200,
                    height: 800,
                    size: 112798,
                    url: 'public/files/anti-virus1_hbLDYXShS.jpg',
                    name: 'anti-virus1_hbLDYXShS.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 613,
                    size: 87796,
                    url: 'public/files/medium_anti-virus1_hbLDYXShS.jpg',
                    name: 'medium_anti-virus1_hbLDYXShS.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 427,
                    size: 50600,
                    url: 'public/files/small_anti-virus1_hbLDYXShS.jpg',
                    name: 'small_anti-virus1_hbLDYXShS.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 227,
                    size: 18424,
                    url: 'public/files/thumbnails_anti-virus1_hbLDYXShS.jpg',
                    name: 'thumbnails_anti-virus1_hbLDYXShS.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 1200,
            height: 800,
            size: 112798,
            url: 'public/files/anti-virus1_hbLDYXShS.jpg',
            name: 'anti-virus1_hbLDYXShS.jpg',
            mimetype: 'image/jpeg',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-02-18T09:26:41.861Z',
            updatedAt: '2022-02-18T09:26:41.861Z',
            id: '620f66519972ac58884523a4',
        },
        createdAt: '2022-02-10T06:50:33.963Z',
        updatedAt: '2022-02-18T09:26:47.471Z',
        id: '6204b5b97d3ba67f4f424fe4',
    },
    {
        isMenu: true,
        visible: true,
        name: 'DISNEY PLUS',
        slug: 'disney-plus',
        description: 'Disneyplus',
        image: {
            formats: {
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 518,
                    size: 22643,
                    url: 'public/files/medium_disney-plus-logo_VFhtIjnTe.jpg',
                    name: 'medium_disney-plus-logo_VFhtIjnTe.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 360,
                    size: 14111,
                    url: 'public/files/small_disney-plus-logo_VFhtIjnTe.jpg',
                    name: 'small_disney-plus-logo_VFhtIjnTe.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 191,
                    size: 5977,
                    url: 'public/files/thumbnails_disney-plus-logo_VFhtIjnTe.jpg',
                    name: 'thumbnails_disney-plus-logo_VFhtIjnTe.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 1440,
            height: 810,
            size: 44613,
            url: 'public/files/disney-plus-logo_VFhtIjnTe.jpg',
            name: 'disney-plus-logo_VFhtIjnTe.jpg',
            mimetype: 'image/jpeg',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-02-10T07:14:20.510Z',
            updatedAt: '2022-02-10T07:14:20.510Z',
            id: '6204bb4c7d3ba67f4f424fef',
        },
        createdAt: '2022-02-10T06:57:32.445Z',
        updatedAt: '2022-02-10T07:14:27.124Z',
        id: '6204b75c7d3ba67f4f424fe9',
    },
    {
        isMenu: true,
        visible: true,
        name: 'SLINGTV',
        slug: 'slingtv',
        description: 'SlingTV giá rẻ',
        image: {
            formats: {
                large: {
                    format: 'png',
                    width: 512,
                    height: 512,
                    size: 17252,
                    url: 'public/files/unnamed (1)_fMkNFnSS1.png',
                    name: 'unnamed (1)_fMkNFnSS1.png',
                    mimetype: 'image/png',
                },
                medium: {
                    format: 'png',
                    width: 512,
                    height: 512,
                    size: 17252,
                    url: 'public/files/unnamed (1)_fMkNFnSS1.png',
                    name: 'unnamed (1)_fMkNFnSS1.png',
                    mimetype: 'image/png',
                },
                small: {
                    format: 'png',
                    width: 512,
                    height: 512,
                    size: 17252,
                    url: 'public/files/unnamed (1)_fMkNFnSS1.png',
                    name: 'unnamed (1)_fMkNFnSS1.png',
                    mimetype: 'image/png',
                },
                thumbnails: {
                    format: 'png',
                    width: 340,
                    height: 340,
                    size: 17684,
                    url: 'public/files/thumbnails_unnamed (1)_fMkNFnSS1.png',
                    name: 'thumbnails_unnamed (1)_fMkNFnSS1.png',
                    mimetype: 'image/png',
                },
            },
            alternativeText: '',
            format: 'png',
            width: 512,
            height: 512,
            size: 17252,
            url: 'public/files/unnamed (1)_fMkNFnSS1.png',
            name: 'unnamed (1)_fMkNFnSS1.png',
            mimetype: 'image/png',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-02-19T03:27:47.185Z',
            updatedAt: '2022-02-19T03:27:47.185Z',
            id: '621063b39972ac588845240a',
        },
        createdAt: '2022-02-19T03:28:05.018Z',
        updatedAt: '2022-02-19T03:28:05.018Z',
        id: '621063c59972ac588845240c',
    },
    {
        isMenu: true,
        visible: true,
        name: 'CURIOSITY STREAM',
        slug: 'curiosity-stream',
        description: 'CURIOSITY STEAM giá rẻ',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 600,
                    height: 400,
                    size: 35687,
                    url: 'public/files/CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    name: 'CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 600,
                    height: 400,
                    size: 35687,
                    url: 'public/files/CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    name: 'CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 600,
                    height: 400,
                    size: 35687,
                    url: 'public/files/CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    name: 'CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 227,
                    size: 6230,
                    url: 'public/files/thumbnails_CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    name: 'thumbnails_CuriosityStream-Logo_J6s6PX9Rz.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 600,
            height: 400,
            size: 35687,
            url: 'public/files/CuriosityStream-Logo_J6s6PX9Rz.jpg',
            name: 'CuriosityStream-Logo_J6s6PX9Rz.jpg',
            mimetype: 'image/jpeg',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-02-19T04:50:07.031Z',
            updatedAt: '2022-02-19T04:50:07.031Z',
            id: '621076ff9972ac5888452417',
        },
        createdAt: '2022-02-19T04:50:16.854Z',
        updatedAt: '2022-02-19T04:50:23.709Z',
        id: '621077089972ac5888452419',
    },
    {
        isMenu: true,
        visible: true,
        name: 'CRUNCHYOLL',
        slug: 'crunchyoll',
        description: 'Crunchyroll giá rẻ, Crunchyroll premium',
        image: {
            formats: {
                large: {
                    format: 'png',
                    width: 1000,
                    height: 750,
                    size: 347583,
                    url: 'public/files/crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    name: 'crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    mimetype: 'image/png',
                },
                medium: {
                    format: 'png',
                    width: 920,
                    height: 690,
                    size: 356138,
                    url: 'public/files/medium_crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    name: 'medium_crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    mimetype: 'image/png',
                },
                small: {
                    format: 'png',
                    width: 640,
                    height: 480,
                    size: 191334,
                    url: 'public/files/small_crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    name: 'small_crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    mimetype: 'image/png',
                },
                thumbnails: {
                    format: 'png',
                    width: 340,
                    height: 255,
                    size: 68449,
                    url: 'public/files/thumbnails_crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    name: 'thumbnails_crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
                    mimetype: 'image/png',
                },
            },
            alternativeText: '',
            format: 'png',
            width: 1000,
            height: 750,
            size: 347583,
            url: 'public/files/crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
            name: 'crunchyroll-khong-hoat-dong-day-la-cach-sua-loi-crunchyroll-khong-tai_0Wr6hhEUQ.png',
            mimetype: 'image/png',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-02-26T14:11:54.712Z',
            updatedAt: '2022-02-26T14:11:54.712Z',
            id: '621a352a9972ac58884527b2',
        },
        createdAt: '2022-02-26T14:12:06.196Z',
        updatedAt: '2022-02-26T14:13:01.751Z',
        id: '621a35369972ac58884527b4',
    },
    {
        isMenu: true,
        visible: true,
        name: 'NBA',
        slug: 'nba',
        description: 'NBA, NBA LEAGUE PASS',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 735,
                    height: 413,
                    size: 36724,
                    url: 'public/files/bg-default-nba-tv_A-5F-9Mq_.jpg',
                    name: 'bg-default-nba-tv_A-5F-9Mq_.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 735,
                    height: 413,
                    size: 36724,
                    url: 'public/files/bg-default-nba-tv_A-5F-9Mq_.jpg',
                    name: 'bg-default-nba-tv_A-5F-9Mq_.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 360,
                    size: 9080,
                    url: 'public/files/small_bg-default-nba-tv_A-5F-9Mq_.jpg',
                    name: 'small_bg-default-nba-tv_A-5F-9Mq_.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 191,
                    size: 3919,
                    url: 'public/files/thumbnails_bg-default-nba-tv_A-5F-9Mq_.jpg',
                    name: 'thumbnails_bg-default-nba-tv_A-5F-9Mq_.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 735,
            height: 413,
            size: 36724,
            url: 'public/files/bg-default-nba-tv_A-5F-9Mq_.jpg',
            name: 'bg-default-nba-tv_A-5F-9Mq_.jpg',
            mimetype: 'image/jpeg',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-05-01T04:20:51.064Z',
            updatedAt: '2022-05-01T04:20:51.064Z',
            id: '626e0aa3ad2695261c92f2d2',
        },
        createdAt: '2022-05-01T04:19:37.423Z',
        updatedAt: '2022-05-01T04:21:11.257Z',
        id: '626e0a59ad2695261c92f2d1',
    },
    {
        isMenu: true,
        visible: true,
        name: 'WWE NETWORK',
        slug: 'wwe-network',
        description: 'WWE NETWORK',
        image: {
            formats: {
                large: {
                    format: 'jpeg',
                    width: 1200,
                    height: 800,
                    size: 24917,
                    url: 'public/files/image001_qO74VXdMP.jpg',
                    name: 'image001_qO74VXdMP.jpg',
                    mimetype: 'image/jpeg',
                },
                medium: {
                    format: 'jpeg',
                    width: 920,
                    height: 613,
                    size: 20540,
                    url: 'public/files/medium_image001_qO74VXdMP.jpg',
                    name: 'medium_image001_qO74VXdMP.jpg',
                    mimetype: 'image/jpeg',
                },
                small: {
                    format: 'jpeg',
                    width: 640,
                    height: 427,
                    size: 12807,
                    url: 'public/files/small_image001_qO74VXdMP.jpg',
                    name: 'small_image001_qO74VXdMP.jpg',
                    mimetype: 'image/jpeg',
                },
                thumbnails: {
                    format: 'jpeg',
                    width: 340,
                    height: 227,
                    size: 5874,
                    url: 'public/files/thumbnails_image001_qO74VXdMP.jpg',
                    name: 'thumbnails_image001_qO74VXdMP.jpg',
                    mimetype: 'image/jpeg',
                },
            },
            alternativeText: '',
            format: 'jpeg',
            width: 1200,
            height: 800,
            size: 24917,
            url: 'public/files/image001_qO74VXdMP.jpg',
            name: 'image001_qO74VXdMP.jpg',
            mimetype: 'image/jpeg',
            user: '61018d512e85c34ebb42b948',
            createdAt: '2022-05-01T04:54:36.989Z',
            updatedAt: '2022-05-01T04:54:36.989Z',
            id: '626e128cad2695261c92f2ec',
        },
        createdAt: '2022-05-01T04:54:47.859Z',
        updatedAt: '2022-05-01T04:54:47.859Z',
        id: '626e1297ad2695261c92f2ee',
    },
];
export const popularProducts = [
    {
        id: 1,
        img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png',
    },
    {
        id: 2,
        img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png',
    },
    {
        id: 3,
        img: 'https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png',
    },
    {
        id: 4,
        img: 'https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png',
    },
    {
        id: 5,
        img: 'https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png',
    },
    {
        id: 6,
        img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png',
    },
    {
        id: 7,
        img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png',
    },
    {
        id: 8,
        img: 'https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png',
    },
];
